import {VehicleLog} from './app.models';

export var logs: Array<VehicleLog> = [
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"12341",
         "bed":{
            "down":false,
            "dirty":true
         }
      },
      "total":12,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"1111111",
         "bed":{
            "down":false,
            "dirty":true
         }
      },
      "total":12,
      "washed":false
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"12342",
         "bed":{
            "down":true,
            "dirty":false
         }
      },
      "total":10,
      "washed":false
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"12341",
         "bed":{
            "down":false,
            "dirty":true
         }
      },
      "total":6,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"car",
         "plate":"12341"
      },
      "total":2.5,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"123truck",
         "bed":{
            "down":true,
            "dirty":false
         }
      },
      "total":10,
      "washed":false
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"123honk",
         "bed":{
            "down":false,
            "dirty":true
         }
      },
      "total":12,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"123honk",
         "bed":{
            "down":false,
            "dirty":true
         }
      },
      "total":6,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"321Beep",
         "bed":{
            "down":false,
            "dirty":false
         }
      },
      "total":10,
      "washed":true
   },
   {
      "vehicle":{
         "vehicleType":"truck",
         "plate":"321Beep",
         "bed":{
            "down":false,
            "dirty":false
         }
      },
      "total":5,
      "washed":true
   }
]